#!/bin/python3

import sys
N = int(input().strip())

if N %2 == 0:  #is even
    if N > 20 or (N>=2 and N<=5):
        print("Not Weird")
    else:
        print("Weird")
else:
        print("Weird")    
    
