#!/bin/python3

import sys
n = int(input().strip())  #Strip method with no arg will remove the white spaces

for i in range(1,11,1): #i: 1->10
    print(n,"x",i,"=",n*i) #or print("{} x {} = {}".format(n, i, (n*i)))
